### ISSUE TITLE
Bug: Filling bottles while holding vials

### ISSUE THREAD

**Issue by arfink** [zabi94/ExtraAlchemy#10] opened 2017-03-16 20:04 UTC
Compile the following template. Fields marked with (*) are mandatory, Fields with (-) are optional, Fields with (!) are mandatory in case of crash or bug

---

#### Type of Issue (Bug / Crash / Suggestion / Translation / ...):
BUG

---

#### Version of the mod or build number:
0.3.0.4 hotfix release

---

#### Minecraft Version (1.9.4, 1.10, 1.10.2...):
1.10.2

---

#### Description of the issue (or what were you doing when it crashed):
Filling empty bottles with water while holding vials in inventory and when inventory is full results in loss of filled bottles.

---

#### [Pastebin](http://pastebin.com) of the log (fml-client-latest.log from your instance/logs folder):
>(!)

---

#### ModPack (or list of mods via [Pastebin](http://pastebin.com). If using a modified modpack, write *BOTH* the modpack AND the link to the _full_ mod list):
http://pastebin.com/Q4nBh8q4

---

#### [Pastebin](http://pastebin.com) of the config file (extraalchemy.cfg from your instance/config folder):
http://pastebin.com/AsCZNVGb

---

#### OS and Java version (Java8 + Windows10 / Java7 + MacOS / ...):
Linux Mint, Java 8 64 bit

---

#### Other information that you think might be useful:
>(-)

**Comment by zabi94** [comment] 2017-04-29 16:10
I cannot reproduce the bug with only my mod installed, nor with a couple other mods of my choice. Some mod in your pack is messing with the way bottles are filled. Closing

**Closed as completed by zabi94** 2017-04-29 16:10 UTC
Labels: Investigate
