### ISSUE TITLE
 Invalid entry in person "contribution" 

### ISSUE THREAD

**Issue by kittech0** [zabi94/ExtraAlchemy#125] opened 2021-12-03 19:55 UTC
**To Reproduce**
Steps to reproduce the crash:
***Just lunch game***

**Pastebin links**
 - Crash Log: https://pastebin.com/cTfiht8t
 - Mod List: https://pastebin.com/zS6Fmuca
 - Extra Alchemy Config: https://pastebin.com/Acp2ipZG

**Environment (please complete the following information):**
 - Mod Version: 1.6.1
 - MC Version: 1.17.1
 - Fabric Version: 0.12.8 (i think)
 - Fabric API version: 0.44.0
 - System: Linux Endevour OS 
 - Installation type: SinglePlayer

**Additional context**
I just lunched a game and it crashed after updating mod.

**Comment by zabi94** [comment] 2021-12-03 19:58
Duplicate of #124

**Closed as completed** 2021-12-03 22:06 UTC
Labels: duplicate
