### ISSUE TITLE
Random server disconnects when potion rings are enabled

### ISSUE THREAD

**Issue by faeldray** [zabi94/ExtraAlchemy#146] opened 2022-11-03 18:23 UTC
**Describe the bug**
I'm running a server with my own modpack on it and a player who was connected and had been playing for a while randomly disconnected and couldn't connect back for more than a few seconds.

On the server, it produced the following error, which wasn't very helpful:
`Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because "$$1" is null`

I had seen this error before when other players had randomly disconnected, but I ignored it because they had always been able to connect again without issue so it didn't seem like a big deal. This was the first time it happened consistently.

We took a look at his latest.log and it seemed like something with REI/potion rings was the issue. After turning off potion rings and restarting the server, he could connect without issue again.

**To Reproduce**
1. Have potion rings enabled
2. ??? - not really sure what exact behaviour triggers the disconnect
3. Disconnects from server

**Expected behavior**
No disconnects

**Pastebin links**
Don't paste the whole lists here, use **pastebin**
 - latest.log: https://pastebin.com/DD3U5GdD (first disconnect error happened at line 9618)
 - Modpack link (preferred) or Mod List: https://modrinth.com/modpack/amethyst-cauldron/
 - Custom changes to modpack (if using a modpack): None
 - Extra Alchemy Config: https://pastebin.com/ZF0naGt4

**Environment (please complete the following information):**
 - Mod Version: 1.8.1
 - MC Version: 1.18.2
 - Quilt Version: 0.17.5-beta.2
 - Fabric API version: 0.59.1 (From https://modrinth.com/mod/qsl/version/1.0.0-beta.26+0.59.1-1.18.2)
 - System: Windows 10
 - Installation type: Client connecting to dedicated server

**Additional context**
This is a Quilt modpack/server so there's some difference from Fabric, but the majority of Fabric mods work on Quilt.

**Comment by zabi94** [comment] 2022-11-03 18:32
I'll look into it. I don't really see how that would cause a disconnect though. Chances are, the error is just a symptom of something else.

I'll just let you know that any fix will be released for the current version though, which at the time I'm writing this is 1.19.2. Just so that you don't hang waiting for a fix that's never coming to your used instance

**Comment by faeldray** [comment] 2022-11-03 18:39
Ah okay. Well then hopefully the issue is something I can fix on my end. Thanks for looking into it anyways.

**Comment by zabi94** [comment] 2023-03-05 10:05
This was a bug caused by a method that populated the creative menu for the mod. The method is no longer used in 1.19.3+ because Minecraft changed the way creative menus are populated, so the bug doesn't exist in newer versions.

**Closed as completed by zabi94** 2023-03-05 10:05 UTC
Labels: bug, interaction bug, Fabric
