### ISSUE TITLE
When recalling from two different dimensions 

### ISSUE THREAD

**Issue by FlickySH** [zabi94/ExtraAlchemy#30] opened 2018-01-16 16:22 UTC
Compile the following template. Fields marked with (*) are mandatory, Fields with (-) are optional, Fields with (!) are mandatory in case of crash or bug

#### Type of Issue/Request (Bug / Crash / Suggestion / Translation / ...):
>(*)

Bug

#### Version of the mod or build number:
>(*)

0.3.6

#### Are you a Single Player, a Multiplayer Client (You are a player in a server) or Server Side?:
>(*)

Single Player

#### Minecraft Version (1.9.4, 1.10, 1.10.2, 1.11.2...):
>(*)

1.12.2

#### Description (or what were you doing when it crashed):
>(*)

I am using Recall II then traveling to the end, when the time is out, it sends me to the overworld, stops the timing but the particles are still there.
It does not happen in the nether.
Have not checked if it happens in multiplayer.
Exiting to the main menu then coming back to the same world stop the particles

#### [Pastebin](http://pastebin.com) of the log (fml-client-latest.log from your instance/logs folder):
>(!)

---

#### ModPack (or list of mods via [Pastebin](http://pastebin.com). If using a modified modpack, write *BOTH* the modpack AND the link to the _full_ mod list):
>(!)

https://pastebin.com/maqmMxHz

#### [Pastebin](http://pastebin.com) of the config file (extraalchemy.cfg from your instance/config folder):
>(!)

https://pastebin.com/5jZX225z

#### OS and Java version (Java8 + Windows10 / Java7 + MacOS / ...):
>(!)

Java 8 + Windows 10

#### Other information that you think might be useful:
>(-)

**Comment by zabi94** [comment] 2018-01-16 16:33
I need the fields marked with (!) to be filled in order to be able to reproduce the issue on my side, you can skip the log one, but versions, config and mod pack are really necessary

**Comment by FlickySH** [comment] 2018-01-16 16:44
Ok providing them

**Comment by FlickySH** [comment] 2018-01-16 16:58
there you go, hope it will be fixed

**Comment by zabi94** [comment] 2018-01-16 18:41
Hm, Minecraft treats the End as a special case when teleporting for some reason. Fixed in next version (hopefully)

**Comment by FlickySH** [comment] 2018-01-16 18:42
ok thx, when it will be on curse?

**Closed as completed by zabi94** 2018-01-16 18:41 UTC
Labels: bug, Investigate, Can't reproduce

**Comment by zabi94** [comment] 2018-01-16 18:46
I'm fixing a couple other bugs, I'm not sure how long it's gonna take, hopefully less than an hour, after that it depends how long will it take to curseforge to approve it

**Comment by FlickySH** [comment] 2018-01-16 18:52
ok thx (btw i LOVE this mod)

**Comment by zabi94** [comment] 2018-01-16 19:05
Glad to hear that! I'm actually planning a complete rewrite, since it's been a port everytime a new version of Minecraft came out since 1.9, and since I've learned how to code better than how I started, so yeah, once I'm done with Bewitchment I'll definitely focus my attention on this mod for a while
