### ISSUE TITLE
[1.17.1] not compatible with Pehkui-3.0.0

### ISSUE THREAD

**Issue by MSandro** [zabi94/ExtraAlchemy#126] opened 2021-12-06 13:08 UTC
**Describe the bug**

**To Reproduce**
1. Create a Fabric 1.17.1 instance (Loader 0.12.8, API 0.44.0)
2. install Pehkui-3.0.0+1.14.4-1.18.jar (it is compatible with older MC Versions too)
3. install extraalchemy-fabric-1.17.1-1.6.1.jar
4. start client
5. it crashes

**Expected behavior**
it should be compatible.

**Comment by zabi94** [comment] 2021-12-06 13:09
Duplicate of #124 and #125

**Closed as completed** 2021-12-06 13:10 UTC
Labels: duplicate

**Comment by MSandro** [comment] 2021-12-21 05:49
any news? I can not find a new version, but all depending issues are closed.

**Comment by zabi94** [comment] 2021-12-21 06:21
The issue is fixed but for some reason the mod won't build on my pc. I'm trying to fix it.
